
server:
  port: 8081

spring:
  application:
    name: helloworld
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/helloworld?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: liwenli
    password: liwenli

mybatis:
  type-aliases-package: com.liwenli.helloworld.entity
  mapper-locations: classpath:/com/liwenli/helloworld/mapper/*.xml

#
#logging:
#  level: debug
#
